name: 🐛 Bug report
description: Create a report to help us improve 🤔.
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: Thank you for reporting!  Please also use the search to see if there are any other relevant issues or pull requests.

  - type: input
    attributes:
      label: Version
      description: Please provide either the release version (*e.g.* `0.1.2`) or the first 7 characters of the `git` commit.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What is happening?
      description: A short description of what is going wrong, in words.
    validations:
      required: true

  - type: textarea
    attributes:
      label: How can we reproduce the issue?
      description: Give some steps that show the bug.  A [minimal working example](https://stackoverflow.com/help/minimal-reproducible-example) of code with output is best.  If you are copying in code, please remember to enclose it in triple backticks (` ``` [multiline code goes here] ``` `) so that it [displays correctly](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax).
    validations:
      required: true

  - type: textarea
    attributes:
      label: What should happen?
      description: A short description, including about the expected output of any code in the previous section.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Any suggestions?
      description: Not required, but if you have suggestions for how a contributor should fix this, or any problems we should be aware of, let us know.
    validations:
      required: false
