name: Build and Deploy Docs Guide
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    name: Docs Guide Build
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Qiskit'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install Non-Python Dependencies
        run: sudo apt-get install -y pandoc graphviz
      - name: Install tox
        run: python -m pip install -U tox
      - name: Test Code Examples
        run: tox run -e doctest
      - name: Build Docs Guide
        run: tox run -e docs-guide
      - name: Bypass Jekyll Processing # Necessary for setting the correct css path
        run: touch docs_guide/_build/html/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs_guide/_build/html # The folder the action should deploy.
