name: Release Artifacts
on:
  push:
    tags:
      - '*'
jobs:
  wheel-build:
    name: Build and Publish Release Artifacts
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    if: github.repository_owner == 'Qiskit'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: '3.11'
      - name: Install Deps
        run: pip install -U build
      - name: Build Artifacts
        run: |
          python -m build
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          path: ./dist/qiskit*
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          path: ./dist/qiskit*
